# -*- coding: utf-8 -*-
"""DL_lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yuGi3JZy_XE6qsE8Nb2nkQ-6a025-lcf
"""

import numpy as np
import math
import pandas as pd
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import cv2

X=[]
for i in range(1,10):
  img1=cv2.imread(('cat.400'+str(i)+'.jpg'))
  img2=cv2.imread(('dog.400'+str(i)+'.jpg'))
  img1=cv2.resize(img1,(500,500))
  img2=cv2.resize(img2,(500,500))
  img1=np.array(img1)
  img2=np.array(img2)
  img1=img1.flatten()
  img2=img2.flatten()
  X.append(img1)
  X.append(img2)

y=np.array([1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0])

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred=logreg.predict(X_test)

score = logreg.score(X_test, y_test)
print(score)

score = logreg.score(X_train, y_train)
print(score)

